### ISSUE TITLE
老哥，看下邮件哈，聊聊实习机会的事儿

### ISSUE THREAD

**Issue by prife** [KernelErr/KernelErr#1]

**Comment by KernelErr** [comment]
您好，感谢您的联系，我已经回复了我的手机号码，不过第一封回复邮件似乎被拒收。如果您未收到我的回复邮件，还麻烦您发送您的微信到我的邮箱。

**Comment by prife** [comment]
回复了你邮件，分别用公司邮箱和我的私人邮箱（gmail），给你发了消息，麻烦看看
